# Generated by Django 6.0.5 on 2026-05-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('remitente_ciudad', models.CharField(max_length=100)),
                ('remitente_depto', models.CharField(blank=True, max_length=100)),
                ('remitente_dir', models.CharField(blank=True, max_length=200)),
                ('remitente_tel', models.CharField(blank=True, max_length=20)),
                ('dest_nombre', models.CharField(max_length=100)),
                ('dest_ciudad', models.CharField(max_length=100)),
                ('dest_depto', models.CharField(blank=True, max_length=100)),
                ('dest_dir', models.CharField(blank=True, max_length=200)),
                ('dest_tel', models.CharField(blank=True, max_length=20)),
                ('dest_peso', models.CharField(blank=True, max_length=30)),
                ('dest_obs', models.TextField(blank=True)),
                ('valor', models.CharField(blank=True, max_length=50)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('paso_actual', models.IntegerField(choices=[(0, 'Envío recogido'), (1, 'En Centro Logístico Origen'), (2, 'Viajando a destino'), (3, 'En Centro Logístico Destino'), (4, 'En camino hacia ti'), (5, 'Entregado')], default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
